version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: lunar-db
    restart: always
    environment:
      POSTGRES_USER: lunar
      POSTGRES_PASSWORD: lunar
      POSTGRES_DB: space_tours
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: