spring:
  application:
    name: lunar

  datasource:
    url: jdbc:postgresql://localhost:5432/space_tours
    username: lunar
    password: lunar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://127.0.0.1:4200
  jwt:
    secret: "change-me-please-change-me-32bytes-min"
    ttl-ms: 86400000